# Generated by Django 4.1.7 on 2023-04-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="webpage", new_name="Webpages",),
    ]
